
<table id="list4" align="center"></table>
<script type="text/javascript">
jQuery("#list4").jqGrid({
	datatype: "json-encode",
	height: 100,
   	colNames:['No','Jabatan', 'Golongan', 'Action'],
   	colModel:[
   		{name:'No',index:'No', width:30, sorttype:"int"},
   		{name:'Jabatan',index:'Jabatan', width:200, sorttype:"char"},
   		{name:'Golongan',index:'Golongan', width:200},
   		{name:'Action',index:'Action', width:100, align:"right",sorttype:"float"},
   			
   	],
   	multiselect: true,
   	caption: "Manipulating Array Data"
});     <?php $idx=0;?>
var mydata = [  
                <?php foreach($this->golongan as $row){$idx++?>
                {    
                     No:"<?php echo $idx?>",
                     Jabatan:"<?php echo $row->jabatan?>",
                     Golongan:"<?php echo $row->golongan?>",
                     Action:"<a href='<?php echo $this->redirect(array('action'=>'delete','id'=>$row->id_jabatan))?>'>Delete</a>"
                },
		<?php }?>
            ];
for(var i=0;i<=mydata.length;i++)
	jQuery("#list4").jqGrid('addRowData',i+1,mydata[i]);
    </script>