<br /><br />
<div id="view-content">

    <table border="1" cellpadding="0" cellspacing="0" align="center" width="100%" class="bgisi">
   
   <tr>
        <td colspan="9" height="30" align="center"> Data Karyawan</td>
   </tr>
   <tr>
        <td align="center" width="5%">No</td>
        <td align="left" width="23%"> Nama</td>
        <td align="center" width="9%">Jenis Kelamin</td>
        <td align="left" width="30%"> TTL</td>
        <td align="center" width="8%">Umur</td>
        <td align="center" width="10%">Departemen</td> 
        <td align="center" width="10%">Jabatan</td>
        <td align="left" width="">Golongan</td>
        <td align="center" width="10%">Action</td>
   </tr>

   <?php $no=0;
   		 
   ?>
    <?php $karyawan = $this->karyawan;?>
    <?php foreach ($karyawan as $row):$no++?>
   <tr>
       <td align="center"><?php echo $no?></td>
       <td><?php echo $row['nama_karyawan']?></td>
       <td align="center"><?php echo $row['jenis_kelamin']?></td>
       <td><?php echo $row['ttl']?></td>
       <td><?php echo $row['umur'].' Thn'?></td>
       <td><?php echo $row['departemen']?></td>
       <td><?php echo $row['jabatan']?></td>
       <td><?php echo $row['golongan']?></td>
       
       <td align="center">
           <a href="/hcgs/jabatan/delete?id=<?php echo $row->id_jabatan?>">Delete</a>
       </td>
   <?php endforeach;?>
   </tr>
   <tr>
       <td colspan="9" align="right">
           <a href="<?php echo $this->url(array('controller'=>'Karyawan','action'=>'insert'))?>"><input type="button" value="Add New"></a>
       </td>
   </tr>




</table>
<script type="text/javascript">
$(document).ready(function() {
   $("#test").tablesorter();
});
</script>
<br>
</div>