
<div id="view-content">
   
  <table border="1" cellpadding="2" cellspacing="1" align="center" width="100%">
      <br>
      
  <tr>
  <h2 colspan="" align="center" >   Data Karyawan </h2>
  </tr> 
  
  <tr>
        <td align="center" width="10%">No</td>
        <td align="left" width="15%">Nama</td>
        <td align="left" width="15%">Departemen</td>
        <td align="left" width="15%">Jabatan</td>
        <td align="left" width="15%">Golongan</td>
        <td align="left" width="15%">Status Pegawai</td> 
        <td align="center" width="15%">action</td>       
  </tr> 
  
   <?php $no=0?>
   <?php foreach ($this->karyawan as $row):$no++?>
 
  <tr>  
       <td align="center"><?php echo $no?></td>
       <td align="left"><?php echo $row->nama_karyawan?></td>
       <td align="left"><?php echo $row->departemen?></td>
       <td align="left"><?php echo $row->jabatan?></td>
       <td align="left"><?php echo $row->golongan?></td>
       <td align="left"><?php echo $row->stat_pegawai?></td> 
      
       <td align="center"> <a href="/hcgs/Karyawan/detail?id=<?php echo $row->id_Karyawan?>">Detail</a></td>
  </tr>       
    <?php endforeach;?>
 
  <tr>
  <p
      <td colspan="4" align="right">
        <a href="<?php echo $this->url(array('controller'=>'Karyawan','action'=>'insert'))?>"><input type="button" value="Add New"></a>
      </td>
  </p>
  </tr>
  </table>
    <br> 
     <br /><br /> 

</div>