<br /><br />
<div id="view-content">

<table border="1" cellpadding="0" cellspacing="0" align="center" width="80%">
   
   <tr>
        <td colspan="3" height="30" align="center"> Data Jabatan</td>
   </tr>
   <tr>
        <td align="center" width="10%">No</td>
        <td align="left" width="70%">Jabatan</td>
        <td align="center" width="20%">Action</td>
   </tr>

   <?php $no=0;
   		 
   ?>
   <?php foreach ($this->jabatan as $row): $no++?>
   <tr>
       <td align="center"><?php echo $no?></td>
       <td><?php echo $row->jabatan?></td>
       <td align="center">
           <a href="/hcgs/jabatan/delete?id=<?php echo $row->id_jabatan?>">Delete</a>
       </td>
   <?php endforeach;?>
   </tr>
   <tr>
       <td colspan="3" align="right">
           <a href="<?php echo $this->url(array('controller'=>'jabatan','action'=>'input'))?>"><input type="button" value="Add New"></a>
       </td>
   </tr>




</table>

 
  
<br>
</div>