<br /><br />
<div id="view-content">

<table border="1" cellpadding="0" cellspacing="0" align="center" width="80%">
   
   <tr>
   		<td colspan="3" height="30" align="center"> Data Jabatan</td>
   </tr>
   <tr>
   		<td>No</td>
   		<td>Jabatan</td>
   		<td>Action</td>
   </tr>

   <?php $no=0;
   		 
   ?>
   <?php foreach ($this->jabatan as $row): $no++?>
   	<tr>
   	<td><?php echo $no?></td>
   	<td><?php echo $row->jabatan?></td>
        <td>
             <a href="/hcgs/jabatan/edit?id=<?php echo $row->id_jabatan?>">Edit</a> ||  
             Delete
        </td>
    <?php endforeach;?>
    </tr>






</table>

 
  
<br>
</div>